name: Datadog Workflow Status
description: Sends workflow duration to Datadog

inputs:
  datadog-api-key:
    required: true

runs:
  using: "node24"
  main: "dist/index.js"
  post: "dist/post/index.js"