name: Repro perf record on Linux ARM

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  repro:
    name: perf record / ${{ matrix.runner }} / run-${{ matrix.run_id }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-24.04-arm
          - ubuntu-22.04-arm
        run_id:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
          - 13
          - 14
          - 15
          - 16
          - 17
          - 18
          - 19
          - 20

    steps:
      - name: Install perf
        run: sudo apt-get install linux-tools-generic
      - name: Enable perf event paranoid flag
        run: sudo sysctl kernel.perf_event_paranoid=1
      - name: Set Kernel KPTR  Restriction
        run: sudo sysctl kernel.kptr_restrict=0
      - name: Run perf command with -a
        run:  sudo perf record -g -e cycles -a -o perf.data sleep 5
      - name: Verify perf output is not empty
        run: |
          perf_output="$(sudo perf script -i perf.data)"
          if [ -z "$perf_output" ]; then
            echo "perf script output is empty"
            exit 1
          fi
          echo "$perf_output"
