name: Build repro

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
    steps:
    - name: Set up repository
      uses: actions/checkout@v4
      with:
        show-progress: false
        fetch-depth: 1
    - name: Install dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-cache policy libglib2.0-dev-bin:i386
        sudo apt-cache policy libglib2.0-dev-bin-linux:i386
        sudo apt-cache policy libglib2.0-dev:i386
        sudo apt-cache policy libsdl2-dev:i386
        sudo apt-mark hold grub-common grub-efi-amd64-bin
        sudo apt-get install -y libsdl2-dev:i386
