name: Minimal macOS clang repro

on:
  workflow_dispatch:

jobs:
  repro:
    strategy:
      matrix:
        os: [macos-14, macos-15, macos-26]
    runs-on: ${{ matrix.os }}
    steps:

      - name: show clang versions
        shell: bash
        run: |
          echo "which clang:   $(which clang)"
          echo "which clang++: $(which clang++)"
          echo
          clang --version
          echo
          clang++ --version

   
