name: Docker check on Ubuntu ARM

on:
  workflow_dispatch:

permissions: {}

jobs:
  docker-check:
    strategy:
      matrix:
        include:
          - runner: ubuntu-22.04-arm
            ubuntu: "22.04"
          - runner: ubuntu-24.04-arm
            ubuntu: "24.04"
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Check docker
        run: |
          which docker || true
          docker version || true
          ls -l /var/run/docker.sock || true

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3
