name: dpkg -l sudo util-linux

on:

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: dpkg -l sudo util-linux
        run: dpkg -l sudo util-linux
