name: Repro npm self-upgrade failure
on:
  workflow_dispatch:

jobs:
  repro:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node 22
        uses: actions/setup-node@v6

      - name: Repro on host
        id: host_repro
        run: |
         sudo npm install -g npm@latest
