name: Show installed Android SDK

on:
  workflow_dispatch:

jobs:
  show-sdk:
    runs-on: ubuntu-24.04

    steps:
      - name: Show installed SDK packages
        run: |
          sdkmanager --list

