on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Example Metrics Job

    steps:
      - name: Set up repository
        uses: actions/checkout@v4

      - uses: .github/actions/datadog-workflow-status
        with:
          datadog-api-key: ${{ secrets.DATADOG_API_KEY }}

      - name: Reproduce snap install issue
        run: |
          time sudo snap install --color=never --unicode=never hello-world
          sleep 10
