name: Compare MSYS2 make

on:
  workflow_dispatch:

jobs:
  direct-msys2-call:
    name: Direct MSYS2 bash call
    runs-on: windows-latest

    steps:

    - name: show version
      shell: pwsh
      run: |
        Write-Host "=== Before PATH change ==="
        Get-Command make.exe -All -ErrorAction SilentlyContinue | Select-Object Source
        make.exe --version

        $env:PATH = "C:\msys64\usr\bin;$env:PATH"

        Write-Host "`n=== After PATH change ==="
        Get-Command make.exe -All | Select-Object Source
        make.exe --version
        Write-Host "`n=== Explicit call ==="
        C:\msys64\usr\bin\make.exe --version
