name: Compare MSYS2 make

on:
  workflow_dispatch:

jobs:
  direct-msys2-call:
    name: Direct MSYS2 bash call
    runs-on: windows-latest

    steps:

      - name: show version
        shell: pwsh
        run: | 
          make.exe --version
          $env:PATH = "C:\msys64\mingw64\bin;C:\msys64\usr\bin;$env:PATH"
          make.exe --version
