name: Windows Free Disk Space Check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  check-disk-space:
    strategy:
      matrix:
        os: [windows-latest, windows-2022, windows-2025]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check free disk space
        shell: pwsh
        run: |
          Get-PSDrive -PSProvider FileSystem | Select-Object Name, @{Name='Used(GB)';Expression={[math]::Round($_.Used/1GB,2)}}, @{Name='Free(GB)';Expression={[math]::Round($_.Free/1GB,2)}}, @{Name='Total(GB)';Expression={[math]::Round(($_.Used+$_.Free)/1GB,2)}}
